name: "elprogramadorgt_blog"
description: "ElProgramadorGT Blog"
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: "docker"
  image: "Dockerfile"

  # name: ci
# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ DOCKER_HUB_USER }}
#           password: ${{ dckr_pat_gUVw9WVtJf1uehFg_vISAV4dan0 }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           tags: elprogramadorgt/blog:latest
